// build.rs

#[cfg(feature = "generate-headers")]
fn generate_headers() {
    use cbindgen::{Builder, Config, Language};
    use std::env;
    use std::path::PathBuf;

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();
    let include_dir = PathBuf::from(&crate_dir).join("include");

    // Make sure the include directory exists
    let _ = std::fs::create_dir_all(&include_dir);

    // --- Config ---
    let mut base_config = Config {
    autogen_warning: Some(
        "/* 
Copyright (c) 2026 NeoHook Authors
SPDX-License-Identifier: MIT OR Apache-2.0

NeoHook: Hook any function with a single line.

NeoHook is a high-performance hooking library for installing inline and IAT hooks on Windows.
By leveraging a transaction-based API, it allows applications to intercept function calls and redirect execution
without modifying the original source code. 

This file is autogenerated by NeoHook. Do not edit manually. */"
            .to_string(),
    ),
    ..Default::default()
};

    // Opaque Struct for DetourTransaction
    base_config
        .export
        .exclude
        .push("DetourTransaction".to_string());
    base_config.after_includes =
        Some("typedef struct DetourTransaction DetourTransaction;".to_string());

    // --- C Header (.h) ---
    let mut c_config = base_config.clone();
    c_config.language = Language::C;
    c_config.include_guard = Some("NEOHOOK_H".to_string());
    c_config.cpp_compat = true;

    let c_output_file = include_dir.join(format!("{}.h", package_name));
    Builder::new()
        .with_crate(&crate_dir)
        .with_config(c_config)
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(c_output_file);
}

fn main() {
    #[cfg(feature = "generate-headers")]
    generate_headers();

    println!("cargo:rerun-if-changed=src/");
}
