#ifndef NEOHOOK_H
#define NEOHOOK_H

/* 
Copyright (c) 2026 NeoHook Authors
SPDX-License-Identifier: MIT OR Apache-2.0

NeoHook: Hook any function with a single line.

NeoHook is a high-performance hooking library for installing inline and IAT hooks on Windows.
By leveraging a transaction-based API, it allows applications to intercept function calls and redirect execution
without modifying the original source code. 

This file is autogenerated by NeoHook. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct DetourTransaction DetourTransaction;

/**
 * Begins a new detour transaction and returns an opaque transaction pointer.
 *
 * The returned pointer is owned by the caller and must later be passed to
 * another transaction API function, such as `detours_transaction_commit`.
 *
 * Returns a non-null pointer on success.
 */
DetourTransaction *detours_transaction_begin(void);

/**
 * Opens, suspends, and tracks the thread identified by `thread_id`.
 *
 * Returns `1` if the transaction pointer is valid and the request was accepted,
 * or `0` if `tx` is null or the transaction is no longer pending.
 *
 * Invalid, inaccessible, or skipped thread IDs are treated as non-fatal and
 * still return `1`, matching NeoHook's best-effort thread tracking behavior.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 */
int32_t detours_transaction_update_thread(DetourTransaction *tx, uint32_t thread_id);

/**
 * Attaches an inline detour to the given transaction.
 *
 *
 * Returns the trampoline pointer for the original function on success, or
 * null on failure.
 *
 * The returned trampoline can be used to call the original function body.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 * `target` and `detour` must be valid pointers to the target function and
 * detour function, respectively.
 */
uint8_t *detours_transaction_attach(DetourTransaction *tx, uint8_t *target, const uint8_t *detour);

/**
 * Commits a detour transaction and returns an opaque handle to the installed
 * hooks.
 *
 * On success, returns a non-null opaque handle that can be queried with
 * `detours_handle_len()` and `detours_handle_get_original_ptr()`, and must
 * eventually be released with `detours_handle_unhook_and_free()`.
 *
 * Returns null if the transaction could not be committed.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. Ownership of `tx` is consumed by this
 * function, regardless of success or failure.
 */
void *detours_transaction_commit(DetourTransaction *tx);

/**
 * Returns the number of installed hooks stored in an opaque hook handle.
 *
 * Returns `0` if `handle` is null.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
uintptr_t detours_handle_len(void *handle);

/**
 * Returns the original function pointer associated with the hook at `idx`.
 *
 * For inline hooks, this is the trampoline entry managed by NeoHook.
 * For IAT hooks, this is the original imported function pointer.
 *
 * Returns null if `handle` is null or if `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
const uint8_t *detours_handle_get_original_ptr(void *handle, uintptr_t idx);

/**
 * Unhooks all installed hooks referenced by `handle` and frees the handle.
 *
 * Dropping the internal hook vector triggers unhooking through RAII.
 *
 * Returns 1 if the handle was accepted for destruction, 0 if null.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
int32_t detours_handle_unhook_and_free(void *handle);

/**
 * Attaches an IAT detour to the given transaction.
 *
 * Returns `1` on success and `0` on failure.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. `h_module` must be a valid module handle
 */
int32_t detours_transaction_attach_iat(DetourTransaction *tx,
                                       void *h_module,
                                       const char *target_dll,
                                       const char *target_func,
                                       const uint8_t *detour);

/**
 * Suspends all threads in the current process except the calling thread and
 * registers them to be resumed later as part of the transaction.
 *
 * Returns `1` if the transaction pointer is valid and the request was accepted,
 * or `0` if `tx` is null or the transaction is no longer pending.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 */
int32_t detours_transaction_update_all_threads(DetourTransaction *tx);

/**
 * Aborts the given transaction, discarding all pending hooks and resuming any
 * tracked threads.
 *
 * Calling this on an already finished transaction has no effect.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. Ownership of `tx` is consumed by this
 * function and it must not be used again afterwards.
 */
int32_t detours_transaction_abort(DetourTransaction *tx);

#endif  /* NEOHOOK_H */
