#ifndef NEOHOOK_H
#define NEOHOOK_H

/* 
Copyright (c) 2026 NeoHook Authors
SPDX-License-Identifier: MIT OR Apache-2.0

NeoHook: Hook any function with a single line.

NeoHook is a high-performance hooking library for installing inline and IAT hooks on Windows.
By leveraging a transaction-based API, it allows applications to intercept function calls and redirect execution
without modifying the original source code. 

This file is autogenerated by NeoHook. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct DetourTransaction DetourTransaction;

/**
 * Maximum number of simultaneously installed INT3 hooks.
 *
 * Unlike VEH hooks (capped at four by the hardware debug registers), the only
 * limit here is the size of the lock-free slot table read by the handler.
 */
#define MAX_HOOKS 256

/**
 * A registered delay / on-load hook.
 *
 * Created with [`DelayHook::register`]. The hook becomes active automatically
 * when its module is loaded (or immediately, if the module is already present).
 * Dropping the guard - or calling [`DelayHook::unhook`] - removes the pending
 * request and, if it was already installed, restores the original byte.
 */
typedef struct DelayHook DelayHook;

/**
 * An installed INT3 software-breakpoint hook.
 *
 * The hook stays active until it is explicitly removed with [`Self::unhook`]
 * or dropped, at which point the original byte is restored and the vectored
 * handler is removed once the last hook is gone.
 */
typedef struct Int3Hook Int3Hook;

/**
 * An installed mid-function detour.
 *
 * Created with [`MidHook::install`]. The detour stays active until the hook is
 * dropped or [`MidHook::unhook`] is called, at which point the original bytes
 * are restored and the context-bridge stub is released.
 */
typedef struct MidHook MidHook;

typedef struct Option_DetoursTamperCallback Option_DetoursTamperCallback;

/**
 * An installed VEH (hardware-breakpoint) hook.
 *
 * The hook stays active until it is explicitly removed with [`Self::unhook`]
 * or dropped, at which point the breakpoint is cleared on every thread and the
 * vectored handler is removed once the last hook is gone.
 */
typedef struct VehHook VehHook;

/**
 * A background guard that reacts to tampered byte patches.
 *
 * Created with [`Self::with_interval`], it spawns a thread that wakes every
 * `interval`, compares each guarded region against its snapshot, and - per the
 * active [`WatchMode`] - rewrites or merely reports any that differ. The thread
 * is stopped and joined when the `Watchdog` is dropped.
 */
typedef struct Watchdog Watchdog;

/**
 * A 128-bit XMM register, captured for a [`MidHook`] handler.
 *
 * The two halves are stored little-endian, matching how `movups` writes the
 * register to memory: `low` is bytes 0..8 (a packed `f64`, the scalar `f32`,
 * or the low quadword of a vector) and `high` is bytes 8..16. A handler reads
 * or writes these directly - e.g. `f64::from_bits(ctx.xmm[0].low)` to read a
 * scalar `double` argument, or `ctx.xmm[0].low = v.to_bits()` to replace it.
 */
typedef struct Xmm {
  /**
   * Bytes 0..8 of the register (the low quadword).
   */
  uint64_t low;
  /**
   * Bytes 8..16 of the register (the high quadword).
   */
  uint64_t high;
} Xmm;

#if defined(_M_X64)
/**
 * Snapshot of the general-purpose registers, flags and SSE / floating-point
 * state at the hook site, captured for an x86_64 [`MidHook`] handler.
 *
 * The field order matches the order in which the stub saves the state, so the
 * pointer passed to the handler aliases this layout exactly. A handler may read
 * any field to observe the live value, or write any field to change the
 * register before the original instructions resume. `rsp` is captured for
 * inspection but writing it has no effect (the stack pointer is managed by the
 * stub).
 *
 * `xmm` holds `XMM0`..`XMM15` in order, and `mxcsr` holds the SSE
 * control/status word. The x87 stack registers are not captured (see the
 * module-level limits).
 *
 * `redirect_rip` is **0 on entry**. Leave it 0 to continue the original
 * function normally; set it to a code address to redirect control flow there
 * instead (see the [module docs](self#control-flow-redirect)).
 */
typedef struct HookContext {
  /**
   * The flags register (`RFLAGS`).
   */
  uint64_t rflags;
  uint64_t rax;
  uint64_t rcx;
  uint64_t rdx;
  uint64_t rbx;
  uint64_t rbp;
  uint64_t rsi;
  uint64_t rdi;
  uint64_t r8;
  uint64_t r9;
  uint64_t r10;
  uint64_t r11;
  uint64_t r12;
  uint64_t r13;
  uint64_t r14;
  uint64_t r15;
  /**
   * The SSE control/status register (`MXCSR`).
   */
  uint32_t mxcsr;
  /**
   * Padding so `xmm` is 8-byte aligned; mirrors a reserved slot in the stub.
   */
  uint32_t _reserved;
  /**
   * `XMM0` through `XMM15`, in register-number order.
   */
  struct Xmm xmm[16];
  /**
   * Control-flow redirect target. `0` (the default) continues the original
   * function; any other value is jumped to after the registers are restored,
   * skipping the stolen instructions. See the [module docs](self#control-flow-redirect).
   */
  uint64_t redirect_rip;
} HookContext;
#endif

#if defined(_M_IX86)
/**
 * Snapshot of the general-purpose registers, flags and SSE / floating-point
 * state at the hook site, captured for an x86 [`MidHook`] handler.
 *
 * The layout matches the `pushad` + `pushfd` block the stub writes, preceded
 * by the saved `MXCSR` and `XMM0`..`XMM7`. Writing `esp` has no effect
 * (`popad` discards its saved stack pointer slot). The x87 stack registers are
 * not captured (see the module-level limits).
 *
 * `redirect_eip` is **0 on entry**. Leave it 0 to continue the original
 * function normally; set it to a code address to redirect control flow there
 * instead (see the [module docs](self#control-flow-redirect)).
 */
typedef struct HookContext {
  /**
   * The flags register (`EFLAGS`).
   */
  uint32_t eflags;
  uint32_t edi;
  uint32_t esi;
  uint32_t ebp;
  uint32_t esp;
  uint32_t ebx;
  uint32_t edx;
  uint32_t ecx;
  uint32_t eax;
  /**
   * The SSE control/status register (`MXCSR`).
   */
  uint32_t mxcsr;
  /**
   * `XMM0` through `XMM7`, in register-number order.
   */
  struct Xmm xmm[8];
  /**
   * Control-flow redirect target. `0` (the default) continues the original
   * function; any other value is jumped to after the registers are restored,
   * skipping the stolen instructions. See the [module docs](self#control-flow-redirect).
   */
  uint32_t redirect_eip;
} HookContext;
#endif

/**
 * A handler invoked at a mid-function hook site with a pointer to the captured
 * [`HookContext`].
 *
 * The handler runs with every general-purpose register, the flags, all XMM
 * registers and `MXCSR` snapshotted and restored around it, so it may freely
 * clobber registers and modify the context block in place. It must not block
 * indefinitely or unwind across the FFI boundary.
 */
typedef void (*MidHookHandler)(struct HookContext *context);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Resolves a function pointer to the first real code address by following
 * common leading jump stubs and import thunks.
 *
 * Returns null if `pointer` is null. If the pointer does not reference a
 * recognized jump stub, the original pointer is returned.
 *
 * # Safety
 * `pointer` and any thunk slots it references must point to readable process
 * memory.
 */
uint8_t *detours_code_from_pointer(const uint8_t *pointer);

/**
 * Begins a new detour transaction and returns an opaque transaction pointer.
 *
 * The returned pointer is owned by the caller and must later be passed to
 * another transaction API function, such as `detours_transaction_commit`.
 *
 * Returns a non-null pointer on success.
 */
DetourTransaction *detours_transaction_begin(void);

/**
 * Opens, suspends, and tracks the thread identified by `thread_id`.
 *
 * Returns `1` if the transaction pointer is valid and the request was accepted,
 * or `0` if `tx` is null or the transaction is no longer pending.
 *
 * Invalid, inaccessible, or skipped thread IDs are treated as non-fatal and
 * still return `1`, matching NeoHook's best-effort thread tracking behavior.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 */
int32_t detours_transaction_update_thread(DetourTransaction *tx, uint32_t thread_id);

/**
 * Attaches an inline detour to the given transaction.
 *
 *
 * Returns the trampoline pointer for the original function on success, or
 * null on failure.
 *
 * The returned trampoline can be used to call the original function body.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 * `target` and `detour` must be valid pointers to the target function and
 * detour function, respectively.
 */
uint8_t *detours_transaction_attach(DetourTransaction *tx, uint8_t *target, const uint8_t *detour);

/**
 * Queues a single hook from an opaque hook handle to be detached when the
 * transaction commits.
 *
 * On success, the selected hook is removed from `handle` during commit. The
 * handle remains valid and any other hooks stored in it remain active.
 *
 * Returns `1` if the detach was queued, or `0` if `tx`/`handle` is null, the
 * transaction is no longer pending, or `idx` is out of bounds.
 *
 * # Safety
 * `tx` must be a valid transaction pointer returned by
 * `detours_transaction_begin()`. `handle` must be a valid handle returned by
 * `detours_transaction_commit()`.
 */
int32_t detours_transaction_detach(DetourTransaction *tx, void *handle, uintptr_t idx);

/**
 * Commits a detour transaction and returns an opaque handle to the installed
 * hooks.
 *
 * On success, returns a non-null opaque handle that can be queried with
 * `detours_handle_len()` and `detours_handle_get_original_ptr()`, and must
 * eventually be released with `detours_handle_unhook_and_free()`.
 *
 * Returns null if the transaction could not be committed.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. Ownership of `tx` is consumed by this
 * function, regardless of success or failure.
 */
void *detours_transaction_commit(DetourTransaction *tx);

/**
 * Returns the number of installed hooks stored in an opaque hook handle.
 *
 * Returns `0` if `handle` is null.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
uintptr_t detours_handle_len(void *handle);

/**
 * Returns the original function pointer associated with the hook at `idx`.
 *
 * For inline hooks, this is the trampoline entry managed by NeoHook.
 * For IAT hooks, this is the original imported function pointer.
 *
 * Returns null if `handle` is null or if `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
const uint8_t *detours_handle_get_original_ptr(void *handle, uintptr_t idx);

/**
 * Enables (`enabled != 0`) or disables (`enabled == 0`) the hook at `idx`
 * without unhooking it.
 *
 * Disabling restores the original code/pointer while keeping the hook
 * installed; enabling re-applies the detour. This is cheaper than a full
 * unhook/rehook cycle.
 *
 * Returns `1` on success, `0` if `handle` is null, `idx` is out of bounds, or
 * the toggle failed.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
int32_t detours_handle_set_enabled(void *handle, uintptr_t idx, int32_t enabled);

/**
 * Returns `1` if the hook at `idx` is currently enabled, `0` otherwise (also
 * `0` if `handle` is null or `idx` is out of bounds).
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
int32_t detours_handle_is_enabled(void *handle, uintptr_t idx);

/**
 * Unhooks all installed hooks referenced by `handle` and frees the handle.
 *
 * Dropping the internal hook vector triggers unhooking through RAII.
 *
 * Returns 1 if the handle was accepted for destruction, 0 if null.
 *
 * # Safety
 * `handle` must be a valid handle previously returned by
 * `detours_transaction_commit()`.
 */
int32_t detours_handle_unhook_and_free(void *handle);

/**
 * Attaches an IAT detour to the given transaction.
 *
 * Returns `1` on success and `0` on failure.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. `h_module` must be a valid module handle
 */
int32_t detours_transaction_attach_iat(DetourTransaction *tx,
                                       void *h_module,
                                       const char *target_dll,
                                       const char *target_func,
                                       const uint8_t *detour);

/**
 * Attaches an EAT detour to the given transaction.
 *
 * Redirects the named export of `h_module` for consumers that resolve it after
 * commit. Returns `1` on success and `0` on failure.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. `h_module` must be a valid module handle and
 * `target_func` must be a valid NUL-terminated C string.
 */
int32_t detours_transaction_attach_eat(DetourTransaction *tx,
                                       void *h_module,
                                       const char *target_func,
                                       const uint8_t *detour);

/**
 * Attaches a VTable detour to the given transaction.
 *
 * Returns the original function pointer in the selected slot on success,
 * or null on failure.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. `vtable` must point to a valid VTable and
 * `index` must refer to an existing slot. `detour` must have a compatible
 * ABI/signature for the selected virtual method.
 */
uint8_t *detours_transaction_attach_vtable(DetourTransaction *tx,
                                           uint8_t **vtable,
                                           uintptr_t index,
                                           const uint8_t *detour);

/**
 * Attaches a per-instance VTable detour to the given transaction.
 *
 * Returns the original function pointer stored in the selected slot on
 * success, or null on failure.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. `object_vptr` must point to the object's
 * vptr field, and `vtable_len` must cover the entire VTable.
 */
uint8_t *detours_transaction_attach_vtable_instance(DetourTransaction *tx,
                                                    uint8_t **object_vptr,
                                                    uintptr_t index,
                                                    uintptr_t vtable_len,
                                                    const uint8_t *detour);

/**
 * Suspends all threads in the current process except the calling thread and
 * registers them to be resumed later as part of the transaction.
 *
 * Returns `1` if the transaction pointer is valid and the request was accepted,
 * or `0` if `tx` is null or the transaction is no longer pending.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`.
 */
int32_t detours_transaction_update_all_threads(DetourTransaction *tx);

/**
 * Aborts the given transaction, discarding all pending hooks and resuming any
 * tracked threads.
 *
 * Calling this on an already finished transaction has no effect.
 *
 * # Safety
 * `tx` must be a valid transaction pointer previously returned by
 * `detours_transaction_begin()`. Ownership of `tx` is consumed by this
 * function and it must not be used again afterwards.
 */
int32_t detours_transaction_abort(DetourTransaction *tx);

/**
 * Enumerates the modules loaded in the calling process.
 *
 * Returns an opaque handle to be queried with `detours_modules_len()` /
 * `detours_modules_*()` and released with `detours_modules_free()`. The handle
 * is non-null even when no modules are reported.
 */
void *detours_enumerate_modules(void);

/**
 * Returns the number of modules in a handle from `detours_enumerate_modules()`.
 *
 * Returns `0` if `handle` is null.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_modules()`.
 */
uintptr_t detours_modules_len(void *handle);

/**
 * Returns the base address (`HMODULE`) of the module at `idx`, or null if
 * `handle` is null or `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_modules()`.
 */
void *detours_modules_base(void *handle, uintptr_t idx);

/**
 * Returns the image size of the module at `idx`, or `0` if `handle` is null or
 * `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_modules()`.
 */
uint32_t detours_modules_size(void *handle, uintptr_t idx);

/**
 * Returns the file name of the module at `idx` as a NUL-terminated string, or
 * null if `handle` is null or `idx` is out of bounds. The pointer is valid
 * until the handle is freed.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_modules()`.
 */
const char *detours_modules_name(void *handle, uintptr_t idx);

/**
 * Frees a module handle returned by `detours_enumerate_modules()`.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_modules()`
 * and must not be used afterwards.
 */
void detours_modules_free(void *handle);

/**
 * Returns the entry point of the module identified by `h_module`.
 *
 * When `h_module` is null, the entry point of the main executable is returned.
 * Returns null if the module headers are invalid or it has no entry point.
 *
 * # Safety
 * `h_module`, when non-null, must be the base address of a valid PE module
 * loaded in the current process.
 */
uint8_t *detours_get_entry_point(void *h_module);

/**
 * Enumerates the exports (EAT) of the module identified by `h_module`.
 *
 * Returns an opaque handle to be queried with `detours_exports_len()` /
 * `detours_exports_*()` and released with `detours_exports_free()`. Returns
 * null if the module's PE headers are invalid.
 *
 * # Safety
 * `h_module` must be the base address of a valid PE module loaded in the
 * current process.
 */
void *detours_enumerate_exports(void *h_module);

/**
 * Returns the number of exports in a handle from `detours_enumerate_exports()`.
 *
 * Returns `0` if `handle` is null.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`.
 */
uintptr_t detours_exports_len(void *handle);

/**
 * Returns the ordinal of the export at `idx`, or `0` if `handle` is null or
 * `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`.
 */
uint32_t detours_exports_ordinal(void *handle, uintptr_t idx);

/**
 * Returns the name of the export at `idx`, or null if it is exported by ordinal
 * only (or `handle` is null / `idx` is out of bounds). Valid until free.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`.
 */
const char *detours_exports_name(void *handle, uintptr_t idx);

/**
 * Returns the resolved code address of the export at `idx`, or null if
 * `handle` is null or `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`.
 */
const uint8_t *detours_exports_address(void *handle, uintptr_t idx);

/**
 * Returns the forwarder target (`"OTHERDLL.Function"`) of the export at `idx`,
 * or null if it is not a forwarder (or `handle` is null / `idx` is out of
 * bounds). Valid until free.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`.
 */
const char *detours_exports_forwarder(void *handle, uintptr_t idx);

/**
 * Frees an export handle returned by `detours_enumerate_exports()`.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_exports()`
 * and must not be used afterwards.
 */
void detours_exports_free(void *handle);

/**
 * Enumerates the imports of the module identified by `h_module` across all of
 * its imported DLLs.
 *
 * Returns an opaque handle to be queried with `detours_imports_len()` /
 * `detours_imports_*()` and released with `detours_imports_free()`. Returns
 * null if the module's PE headers are invalid.
 *
 * # Safety
 * `h_module` must be the base address of a valid PE module loaded in the
 * current process.
 */
void *detours_enumerate_imports(void *h_module);

/**
 * Returns the number of imports in a handle from `detours_enumerate_imports()`.
 *
 * Returns `0` if `handle` is null.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`.
 */
uintptr_t detours_imports_len(void *handle);

/**
 * Returns the source DLL name of the import at `idx`, or null if `handle` is
 * null or `idx` is out of bounds. Valid until free.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`.
 */
const char *detours_imports_dll(void *handle, uintptr_t idx);

/**
 * Returns the name of the import at `idx`, or null if it is imported by ordinal
 * (or `handle` is null / `idx` is out of bounds). Valid until free.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`.
 */
const char *detours_imports_name(void *handle, uintptr_t idx);

/**
 * Returns the ordinal of the import at `idx`, or `0xFFFFFFFF` if it is imported
 * by name (or `handle` is null / `idx` is out of bounds).
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`.
 */
uint32_t detours_imports_ordinal(void *handle, uintptr_t idx);

/**
 * Returns the bound IAT address of the import at `idx`, or null if `handle` is
 * null or `idx` is out of bounds.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`.
 */
const uint8_t *detours_imports_address(void *handle, uintptr_t idx);

/**
 * Frees an import handle returned by `detours_enumerate_imports()`.
 *
 * # Safety
 * `handle` must be a valid handle returned by `detours_enumerate_imports()`
 * and must not be used afterwards.
 */
void detours_imports_free(void *handle);

/**
 * Resolves an exported function by name within a module, loading the module if
 * it is not already present.
 *
 * Returns null if `module`/`func` are null or not valid UTF-8, or if the
 * function cannot be resolved.
 *
 * # Safety
 * `module` and `func` must be valid NUL-terminated C strings.
 */
const uint8_t *detours_find_function(const char *module, const char *func);

/**
 * Resolves `symbol` within `module` to its absolute address using `dbghelp`,
 * covering PDB symbols (when symbols are available) as well as exports - so
 * non-exported functions can be located by name.
 *
 * Returns null if either argument is null or not valid UTF-8, `dbghelp` cannot
 * initialize, the module cannot be found, or the symbol is unknown.
 *
 * # Safety
 * `module` and `symbol` must be valid NUL-terminated C strings.
 */
const uint8_t *detours_resolve_symbol(const char *module, const char *symbol);

/**
 * Resolves an exported function by ordinal within a module, loading the module
 * if it is not already present.
 *
 * Returns null if `module` is null or not valid UTF-8, or if the ordinal
 * cannot be resolved.
 *
 * # Safety
 * `module` must be a valid NUL-terminated C string.
 */
const uint8_t *detours_find_function_by_ordinal(const char *module, uint16_t ordinal);

/**
 * Resolves a byte signature inside the module identified by `h_module`,
 * returning the address of the first match in its executable regions.
 *
 * `pattern` is an IDA / x64dbg-style signature string (e.g.
 * `"48 8B 05 ?? ?? ?? ?? E8"`). Returns null if `pattern` is null, not valid
 * UTF-8, not a valid signature, or does not match.
 *
 * # Safety
 * `h_module` must be the base address of a valid PE module loaded in the
 * current process, and `pattern` must be a valid NUL-terminated C string.
 */
const uint8_t *detours_scan_module(void *h_module, const char *pattern);

/**
 * Resolves a byte signature inside a module identified by name, loading the
 * module if it is not already present.
 *
 * Returns the address of the first match in the module's executable regions,
 * or null if `module`/`pattern` are null, not valid UTF-8, `pattern` is not a
 * valid signature, or it does not match.
 *
 * # Safety
 * `module` and `pattern` must be valid NUL-terminated C strings.
 */
const uint8_t *detours_scan_module_by_name(const char *module, const char *pattern);

/**
 * Scans `len` bytes starting at `start` for the first occurrence of a byte
 * signature, limited to committed, readable regions.
 *
 * `pattern` is an IDA / x64dbg-style signature string. Returns null if
 * `start`/`pattern` are null, `pattern` is not valid UTF-8 or not a valid
 * signature, or it does not match.
 *
 * # Safety
 * `start` must point into this process's address space, and `pattern` must be
 * a valid NUL-terminated C string.
 */
const uint8_t *detours_scan_range(const uint8_t *start, uintptr_t len, const char *pattern);

/**
 * Resolves a byte signature inside a module and queues an inline hook on the
 * matched address.
 *
 * On success, returns the trampoline pointer for calling the original. Returns
 * null if `tx`/`module`/`pattern` are null, the arguments are not valid UTF-8,
 * `pattern` is not a valid signature, it does not match, or the hook could not
 * be prepared.
 *
 * # Safety
 * `tx` must be a valid transaction pointer returned by
 * `detours_transaction_begin()`, and `module`/`pattern` must be valid
 * NUL-terminated C strings.
 */
uint8_t *detours_transaction_attach_pattern(DetourTransaction *tx,
                                            const char *module,
                                            const char *pattern,
                                            const uint8_t *detour);

/**
 * Resolves an exported function by name and queues an inline hook on it.
 *
 * Convenience entry point combining `detours_find_function` and
 * `detours_transaction_attach`: loads `module` if needed, resolves `func`, and
 * queues an inline hook on the function body (intercepting every caller).
 *
 * On success, returns the trampoline pointer for calling the original. Returns
 * null if `tx`/`module`/`func` are null, the arguments are not valid UTF-8, the
 * export could not be resolved, or the hook could not be prepared.
 *
 * # Safety
 * `tx` must be a valid transaction pointer returned by
 * `detours_transaction_begin()`, and `module`/`func` must be valid
 * NUL-terminated C strings.
 */
uint8_t *detours_transaction_attach_export(DetourTransaction *tx,
                                           const char *module,
                                           const char *func,
                                           const uint8_t *detour);

/**
 * Installs a VEH (hardware-breakpoint) hook redirecting `target` to `detour`.
 *
 * Returns an opaque hook pointer on success, or null on failure (null
 * arguments, all four breakpoint slots in use, the target already hooked, or
 * handler registration failure). The returned pointer must be released with
 * `detours_veh_unhook`.
 *
 * # Safety
 * `target` must point at the entry of a real function in executable memory and
 * `detour` must be a function pointer with a compatible ABI/signature.
 */
struct VehHook *detours_veh_install(const uint8_t *target, const uint8_t *detour);

/**
 * Installs a VEH hook that also exposes a callable gateway to the original
 * function, retrievable with `detours_veh_original`.
 *
 * Behaves like `detours_veh_install`, but lets the detour forward to the
 * original (e.g. to use its return value) without re-triggering the
 * breakpoint. Returns null on failure, including when the original gateway
 * could not be built. The returned pointer must be released with
 * `detours_veh_unhook`.
 *
 * # Safety
 * `target` must point at the entry of a real function in executable memory and
 * `detour` must be a function pointer with a compatible ABI/signature.
 */
struct VehHook *detours_veh_install_with_original(const uint8_t *target, const uint8_t *detour);

/**
 * Returns the callable original-function pointer for a VEH hook installed with
 * `detours_veh_install_with_original`, or null if `hook` is null or was
 * installed without a gateway.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by `detours_veh_install*`
 * and still live (not yet unhooked).
 */
const uint8_t *detours_veh_original(const struct VehHook *hook);

/**
 * Removes a VEH hook installed by `detours_veh_install` and frees it.
 *
 * Returns `1` if the hook was accepted for removal, or `0` if `hook` is null.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by `detours_veh_install`
 * and must not be used afterwards.
 */
int32_t detours_veh_unhook(struct VehHook *hook);

/**
 * Installs a mid-function / arbitrary-address detour redirecting `target` to
 * the context handler `handler`.
 *
 * Unlike entry-point hooks, `target` may be any instruction boundary. The
 * handler is called with a pointer to a `HookContext` snapshot of the
 * general-purpose registers and flags, which it may read or modify before the
 * original instructions resume.
 *
 * Returns an opaque hook pointer on success, or null on failure (null
 * arguments, allocation failure, or non-relocatable bytes at `target`). The
 * returned pointer must be released with `detours_midhook_unhook`.
 *
 * # Safety
 * `target` must point at the start of a real instruction in executable memory,
 * and `handler` must be a valid context-handler function pointer.
 */
struct MidHook *detours_midhook_install(const uint8_t *target, MidHookHandler handler);

/**
 * Removes a mid-function detour installed by `detours_midhook_install` and
 * frees it, restoring the original bytes at the target.
 *
 * Returns `1` if the hook was accepted for removal, or `0` if `hook` is null.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by
 * `detours_midhook_install` and must not be used afterwards.
 */
int32_t detours_midhook_unhook(struct MidHook *hook);

/**
 * Installs an INT3 (software-breakpoint) hook redirecting `target` to `detour`.
 *
 * Patches a single `0xCC` byte at `target` and routes the resulting breakpoint
 * through a vectored exception handler. Unlike `detours_veh_install`, there is
 * no four-hook limit (up to `INT3_MAX_HOOKS` targets) and threads created after
 * the install still trap.
 *
 * Returns an opaque hook pointer on success, or null on failure (null
 * arguments, all slots in use, the target already hooked, handler registration
 * failure, or the patch byte could not be written). The returned pointer must
 * be released with `detours_int3_unhook`.
 *
 * # Safety
 * `target` must point at the entry of a real function in executable memory and
 * `detour` must be a function pointer with a compatible ABI/signature.
 */
struct Int3Hook *detours_int3_install(const uint8_t *target, const uint8_t *detour);

/**
 * Installs an INT3 hook that also exposes a callable gateway to the original
 * function, retrievable with `detours_int3_original`.
 *
 * Behaves like `detours_int3_install`, but lets the detour forward to the
 * original (e.g. to use its return value) without re-triggering the
 * breakpoint. Returns null on failure, including when the original gateway
 * could not be built. The returned pointer must be released with
 * `detours_int3_unhook`.
 *
 * # Safety
 * `target` must point at the entry of a real function in executable memory and
 * `detour` must be a function pointer with a compatible ABI/signature.
 */
struct Int3Hook *detours_int3_install_with_original(const uint8_t *target, const uint8_t *detour);

/**
 * Returns the callable original-function pointer for an INT3 hook installed
 * with `detours_int3_install_with_original`, or null if `hook` is null or was
 * installed without a gateway.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by `detours_int3_install*`
 * and still live (not yet unhooked).
 */
const uint8_t *detours_int3_original(const struct Int3Hook *hook);

/**
 * Removes an INT3 hook installed by `detours_int3_install` and frees it,
 * restoring the original byte at the target.
 *
 * Returns `1` if the hook was accepted for removal, or `0` if `hook` is null.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by `detours_int3_install`
 * and must not be used afterwards.
 */
int32_t detours_int3_unhook(struct Int3Hook *hook);

/**
 * Resolves the absolute target of a near branch (`call`/`jmp`/`jcc rel`) at
 * `addr` by decoding the instruction.
 *
 * Returns the branch target, or null if `addr` is null/unreadable, does not
 * decode, or is not a near-branch instruction.
 *
 * # Safety
 * `addr` must point into this process's address space.
 */
const uint8_t *detours_resolve_call_target(const uint8_t *addr);

/**
 * Resolves the absolute address referenced by a RIP-relative memory operand at
 * `addr` (e.g. `lea`/`mov [rip+disp32]`) by decoding the instruction.
 *
 * Returns the referenced address, or null if `addr` is null/unreadable, does
 * not decode, or has no RIP-relative operand.
 *
 * # Safety
 * `addr` must point into this process's address space.
 */
const uint8_t *detours_resolve_rip_relative(const uint8_t *addr);

/**
 * Resolves a relative reference from its raw encoding: returns
 * `addr + instr_len + *(int32_t*)(addr + disp_offset)`.
 *
 * # Safety
 * `addr` must be readable for at least `disp_offset + 4` bytes.
 */
const uint8_t *detours_resolve_relative(const uint8_t *addr,
                                        uintptr_t disp_offset,
                                        uintptr_t instr_len);

/**
 * Registers a delay / on-load hook that installs automatically when `module` is
 * loaded (or immediately, if it is already present).
 *
 * Returns an opaque hook pointer on success, or null on failure (null
 * arguments, not valid UTF-8, or the one-time `LdrLoadDll` hook failed). The
 * returned pointer must be released with `detours_delay_unhook`.
 *
 * # Safety
 * `module` and `func` must be valid NUL-terminated C strings, and `detour` must
 * be a function pointer with an ABI/signature compatible with the eventual
 * target (full replacement, no trampoline).
 */
struct DelayHook *detours_delay_register(const char *module,
                                         const char *func,
                                         const uint8_t *detour);

/**
 * Returns `1` if the delay hook's module has been loaded and the hook is now
 * installed, or `0` if it is still pending (or `hook` is null).
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by
 * `detours_delay_register`.
 */
int32_t detours_delay_is_active(const struct DelayHook *hook);

/**
 * Removes a delay hook registered by `detours_delay_register` and frees it,
 * restoring the original byte if it had already been installed.
 *
 * Returns `1` if the hook was accepted for removal, or `0` if `hook` is null.
 *
 * # Safety
 * `hook` must be a valid pointer previously returned by
 * `detours_delay_register` and must not be used afterwards.
 */
int32_t detours_delay_unhook(struct DelayHook *hook);

/**
 * Creates an anti-tamper watchdog whose background thread re-applies tampered
 * byte patches every `interval_ms` milliseconds.
 *
 * Returns an opaque watchdog pointer (non-null), which must later be released
 * with `detours_watchdog_destroy`. An `interval_ms` of `0` is treated as 1 ms.
 */
struct Watchdog *detours_watchdog_create(uint32_t interval_ms);

/**
 * Snapshots `len` bytes at `target` and guards them, returning a non-zero guard
 * id usable with `detours_watchdog_unguard`.
 *
 * Install the hook first: the bytes are read now and become the image the
 * watchdog re-applies. Returns `0` if `wd`/`target` is null or `len` is zero.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer from `detours_watchdog_create`, and
 * `target` must point at `len` readable bytes for the lifetime of the guard.
 */
uint64_t detours_watchdog_guard(struct Watchdog *wd, const uint8_t *target, uintptr_t len);

/**
 * Stops guarding the region identified by `id`.
 *
 * Returns `1` if a matching region was being guarded, `0` otherwise (including
 * when `wd` is null). Call this before unhooking the target.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer from `detours_watchdog_create`.
 */
int32_t detours_watchdog_unguard(struct Watchdog *wd, uint64_t id);

/**
 * Returns how many times the watchdog has rewritten a tampered region since it
 * was created, or `0` if `wd` is null.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer from `detours_watchdog_create`.
 */
uint64_t detours_watchdog_restorations(const struct Watchdog *wd);

/**
 * Sets the watchdog's reaction to tampering: re-apply the patch
 * (`detect_only == 0`, the default) or only report it (`detect_only != 0`).
 *
 * Returns `1` on success, or `0` if `wd` is null.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer from `detours_watchdog_create`.
 */
int32_t detours_watchdog_set_mode(const struct Watchdog *wd, int32_t detect_only);

/**
 * Installs (`cb != NULL`) or clears (`cb == NULL`) the tamper callback. The
 * callback runs on the watchdog's background thread.
 *
 * Returns `1` on success, or `0` if `wd` is null.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer from `detours_watchdog_create`. `cb`,
 * when non-null, must be callable for the watchdog's lifetime, and `user` is
 * passed through unchanged on every invocation.
 */
int32_t detours_watchdog_set_on_tamper(const struct Watchdog *wd,
                                       struct Option_DetoursTamperCallback cb,
                                       void *user);

/**
 * Stops the watchdog's background thread and frees it.
 *
 * Returns `1` if the watchdog was accepted for destruction, or `0` if null.
 *
 * # Safety
 * `wd` must be a valid watchdog pointer previously returned by
 * `detours_watchdog_create` and must not be used afterwards.
 */
int32_t detours_watchdog_destroy(struct Watchdog *wd);

/**
 * Returns `1` if NeoHook will register Control Flow Guard call targets for this
 * process, `0` otherwise.
 *
 * Reflects a `detours_cfg_set_enforcement` override if one is set, otherwise the
 * process's CFG mitigation policy. See [`crate::cfg`].
 */
int32_t detours_cfg_is_enforced(void);

/**
 * Overrides CFG handling: `mode < 0` returns to auto-detection, `mode == 0`
 * forces it off (the whole layer becomes a no-op), `mode > 0` forces it on.
 */
void detours_cfg_set_enforcement(int32_t mode);

/**
 * Marks `entry` as a valid Control Flow Guard indirect-call target, so
 * runtime-generated code can be reached through a guarded indirect call.
 *
 * Returns `1` if the target was registered, `0` if registration was skipped
 * (CFG not enforced) or `entry` is null. See [`crate::cfg::register_valid_target`].
 *
 * # Safety
 * `entry` must point at the entry of executable, committed memory.
 */
int32_t detours_cfg_register_valid_target(const uint8_t *entry);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NEOHOOK_H */
