name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v4

      - name: Install x86 target
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add ${{ matrix.target }}
      
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Show toolchain
        run: rustc -Vv && cargo -V

      - name: Check formatting
        run: cargo fmt --all -- --check

      #- name: Clippy
        #run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --target ${{ matrix.target }} --all-features -- --test-threads=1

      - name: Build release
        run: cargo build --release

      - name: Build docs
        run: cargo doc --no-deps